"""Emit the ESPHome YAML for a validated Panel.

Everything the panel draws is produced here, including the minimal per-size MDI
glyph lists. Nothing downstream invents a coordinate or a codepoint.
"""
from . import icons, layout as L
from .config import Light, Climate, Readout

HEAD = """# AUTO-GENERATED by tools/panel - DO NOT EDIT.
# Source: panel.yaml   Regenerate with: tools/panel build
"""


def _q(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _lit(esc):
    """Quote an already-formed \\U000F.... escape WITHOUT re-escaping its backslash.

    _q is for human text. Using it on a glyph escape yields "\\\\U000F0336", which
    YAML decodes to the literal ten characters rather than the icon - it compiles
    happily and draws nonsense on the panel.
    """
    return '"' + esc + '"'


class Emitter:
    def __init__(self, panel):
        self.p = panel
        self.g = icons.GlyphSets()
        self.out = []
        self.sensors = []
        self.text_sensors = []
        self.binary_sensors = []
        self.pages = []          # (title, icon, page_id)
        self.scripts = []
        self.intervals = []
        self.globals = []

    # ---------------------------------------------------------------- helpers
    def w(self, s=""):
        self.out.append(s)

    def card(self, x, y, w, h, pad=14, extra=()):
        b = [f"        - obj:", "            styles: tile", "            scrollable: false",
             f"            x: {x}", f"            y: {y}",
             f"            width: {w}", f"            height: {h}",
             f"            pad_all: {pad}"]
        b += [f"            {e}" for e in extra]
        b.append("            widgets:")
        return b

    def button(self, x, y, w, h, style="navbtn", extra=()):
        b = [f"        - button:", f"            styles: {style}",
             "            pressed: { styles: tile_on }",
             f"            x: {x}", f"            y: {y}",
             f"            width: {w}", f"            height: {h}"]
        b += [f"            {e}" for e in extra]
        return b

    # ------------------------------------------------------------------ pages
    def build(self):
        seq = []
        for pi, page in enumerate(self.p.pages):
            fn = getattr(self, f"_page_{page.type}")
            seq.extend(fn(pi, page))
        seq.extend(self._page_settings(len(self.p.pages)))

        nav = L.paginate_nav(len(seq), bool(self.p.summary))
        home = self._page_home(nav, seq)
        self.pages = home + seq
        return self._assemble()

    # -- Home ---------------------------------------------------------------
    def _page_home(self, nav_pages, seq):
        out = []
        for hp, tiles in enumerate(nav_pages):
            pid = f"page_home{'' if hp == 0 else hp + 1}"
            body = [f"    - id: {pid}", "      bg_color: ${paper}", "      bg_opa: COVER",
                    "      on_load:",
                    f"        - lambda: 'if (id(ui_ready)) id(last_page) = {len(out)};'"]
            if self.p.summary and hp == 0:
                body.append("        - script.execute: home_summary")
            body.append("      widgets:")
            for t in tiles:
                title, icon, target = seq[t.item][:3]
                self.g.add("icon_l", icon)
                body += self.button(t.x, t.y, t.w, t.h, "tile", extra=[
                    "pad_all: 6", "layout:", "  type: FLEX", "  flex_flow: COLUMN",
                    "  flex_align_main: CENTER", "  flex_align_cross: CENTER",
                    "  flex_align_track: CENTER", "  pad_row: 8", "widgets:",
                    f"  - label: {{ text: {_lit(icons.escape(icon))}, text_font: icon_l }}",
                    f"  - label: {{ text: {_q(title)}, text_font: font_m }}",
                    "on_press:", "  - script.execute: inactivity",
                    f"  - lvgl.page.show: {target}"])
            if self.p.summary and hp == 0:
                body += self._summary_card()
            out.append(("Home" if hp == 0 else f"Home {hp+1}", "home", pid, body))
        return [(t, i, p, b) for t, i, p, b in out]

    def _summary_card(self):
        cells, body = self.p.summary, self.card(L.MARGIN, L.SUMMARY_Y, L.CONTENT_W, L.SUMMARY_H)
        checks = []
        for i, c in enumerate(cells):
            x, y = (0 if i % 2 == 0 else 200), (0 if i < 2 else 116)
            body += [f"              - label: {{ x: {x}, y: {y}, text: {_q(c.label)}, text_font: font_s }}",
                     "              - label:", f"                  id: sum{i}_val",
                     f"                  x: {x}", f"                  y: {y + 28}",
                     "                  text_font: font_l", "                  text: !lambda |-"]
            if c.source == "lights_on":
                ids = ", ".join(f"id({e})" for e in self._light_state_ids())
                body += [f"                    int v = 0;",
                         f"                    for (auto *t : {{{ids}}}) if (t->state == \"on\") v++;",
                         f"                    return str_sprintf(\"%d on\", v);"]
                checks.append((i, f"""int v = 0;
              for (auto *t : {{{ids}}}) if (t->state == "on") v++;
              if (v == id(sum{i}_shown)) return false;
              id(sum{i}_shown) = v;
              return true;"""))
            else:
                sid = self._sensor(c.entity, c.attribute)
                body += [f"                    const float x = id({sid}).state;",
                         f"                    return std::isnan(x) ? std::string(\"--\") : str_sprintf({_q(c.format)}, x);"]
                checks.append((i, f"""const float x = id({sid}).state;
              const int v = std::isnan(x) ? -99999 : (int) lroundf(x * 100.0f);
              if (v == id(sum{i}_shown)) return false;
              id(sum{i}_shown) = v;
              return true;"""))
            self.globals.append(f"  - id: sum{i}_shown\n    type: int\n    initial_value: \"-99999\"")

        s = ["  - id: home_summary", "    then:"]
        for i, cond in checks:
            s += ["      - if:", "          condition:", "            lambda: |-",
                  *[f"              {ln}" for ln in cond.strip().splitlines()],
                  f"          then: [ lvgl.widget.refresh: sum{i}_val ]"]
        self.scripts.append("\n".join(s))
        self.intervals.append(
            "  - interval: 30s\n    then:\n      - if:\n          condition:\n"
            "            lambda: 'return lv_screen_active() == id(page_home)->obj;'\n"
            "          then: [ script.execute: home_summary ]")
        return body

    def _light_state_ids(self):
        ids = []
        for pi, page in enumerate(self.p.pages):
            if page.type == "lights":
                ids += [f"p{pi}e{ei}_state" for ei in range(len(page.entities))]
        return ids or ["battery_level"]        # never emit an empty initialiser list

    # -- Lights -------------------------------------------------------------
    def _page_lights(self, pi, page):
        out = []
        for sp, placed in enumerate(L.paginate_lights(page.entities)):
            pid = f"page_p{pi}_{sp}"
            title = page.title if sp == 0 else f"{page.title} {sp + 1}"
            body = [f"    - id: {pid}", "      bg_color: ${paper}", "      bg_opa: COVER",
                    "      on_load:", "        - lambda: 'if (id(ui_ready)) id(last_page) = PAGEIDX;'",
                    "      widgets:"]
            for t in placed:
                e = t.item
                ei = page.entities.index(e)
                on, off = icons.escape(e.icon_on), icons.escape(e.icon_off)
                self.g.add("icon_m", e.icon_on, e.icon_off)
                tid, iid = f"p{pi}e{ei}_tile", f"p{pi}e{ei}_icon"
                body += self.button(t.x, t.y, t.w, t.h, "tile", extra=[
                    "pad_all: 6", f"id: {tid}", "checked: { styles: tile_on }",
                    "layout:", "  type: FLEX", "  flex_flow: COLUMN",
                    "  flex_align_main: CENTER", "  flex_align_cross: CENTER",
                    "  flex_align_track: CENTER", "  pad_row: 2", "widgets:",
                    f"  - label: {{ id: {iid}, text: {_lit(off)}, text_font: icon_m }}",
                    f"  - label: {{ text: {_q(e.label)}, text_font: font_s, long_mode: WRAP,"
                    f" width: {t.w - 14}, text_align: CENTER }}",
                    "on_press:",
                    f"  - lvgl.widget.update:", f"      id: {tid}", "      state:",
                    f"        checked: !lambda 'return !lv_obj_has_state(id({tid}), LV_STATE_CHECKED);'",
                    f"  - lvgl.label.update:", f"      id: {iid}",
                    f"      text: !lambda 'return std::string(lv_obj_has_state(id({tid}), LV_STATE_CHECKED)"
                    f" ? \"{on}\" : \"{off}\");'",
                    "  - script.execute: inactivity",
                    "  - homeassistant.action:", "      action: light.toggle",
                    f"      data: {{ entity_id: {e.entity} }}"])
                self.text_sensors.append(
                    f"  - platform: homeassistant\n    id: p{pi}e{ei}_state\n"
                    f"    entity_id: {e.entity}\n    on_value:\n"
                    f"      - lvgl.widget.update:\n          id: {tid}\n          state:\n"
                    f"            checked: !lambda 'return x == \"on\";'\n"
                    f"      - lvgl.label.update:\n          id: {iid}\n"
                    f"          text: !lambda 'return std::string(x == \"on\" ? \"{on}\" : \"{off}\");'")
                if e.dim:
                    sy = t.extra["stepper_y"]
                    for k, (sign, delta) in enumerate((("\\u2212", -e.step), ("+", e.step))):
                        body += self.button(t.x + k * (L.STEPPER_W + L.STEPPER_GAP), sy,
                                            L.STEPPER_W, L.STEPPER_H, extra=[
                            f"widgets: [ {{ label: {{ align: CENTER, text: \"{sign}\","
                            " text_font: font_step } } ]",
                            "on_press:", "  - script.execute: inactivity",
                            "  - homeassistant.action:", "      action: light.turn_on",
                            f"      data: {{ entity_id: {e.entity}, brightness_step_pct: \"{delta}\" }}"])
            out.append((title, page.icon, pid, body))
        return out

    # -- Climate ------------------------------------------------------------
    def _page_climate(self, pi, page):
        out = []
        for sp, placed in enumerate(L.paginate_climate(page.entities)):
            pid = f"page_p{pi}_{sp}"
            title = page.title if sp == 0 else f"{page.title} {sp + 1}"
            body = [f"    - id: {pid}", "      bg_color: ${paper}", "      bg_opa: COVER",
                    "      on_load:", "        - lambda: 'if (id(ui_ready)) id(last_page) = PAGEIDX;'",
                    "        - lvgl.widget.refresh: [" +
                    ", ".join(f"p{pi}e{page.entities.index(t.item)}_{k}"
                              for t in placed for k in ("now", "set")) + "]",
                    "      widgets:",
                    f"        - label: {{ x: {L.MARGIN}, y: {L.HEADING_Y}, styles: heading,"
                    f" text: {_q(page.title)} }}"]
            for t in placed:
                e = t.item
                ei = page.entities.index(e)
                self.g.add("icon_m", e.icon)
                body += self.card(t.x, t.y, t.w, t.h) + [
                    f"              - label: {{ x: 0, y: 2, text: {_lit(icons.escape(e.icon))}, text_font: icon_m }}",
                    f"              - label: {{ x: 48, y: 6, text: {_q(e.label)}, text_font: font_m }}",
                    "              - label:", f"                  id: p{pi}e{ei}_set",
                    "                  align: TOP_RIGHT", "                  text_font: font_l",
                    f"                  text: !lambda 'const float v = id(p{pi}e{ei}_target).state;"
                    f" return std::isnan(v) ? std::string(\"--\") : str_sprintf(\"%.1f\\u00B0\", v);'",
                    "              - label:", f"                  id: p{pi}e{ei}_now",
                    "                  x: 0", "                  y: 62", "                  text_font: font_s",
                    f"                  text: !lambda 'const float v = id(p{pi}e{ei}_current).state;"
                    f" return std::isnan(v) ? std::string(\"Now --\") : str_sprintf(\"Now %.1f\\u00B0\", v);'"]
                inner_w = (t.w - 6 - 28 - 14) // 2
                for k, (sign, delta) in enumerate((("\\u2212", -e.step), ("+", e.step))):
                    body += [f"              - button:", "                  styles: navbtn",
                             "                  pressed: { styles: tile_on }",
                             f"                  x: {k * (inner_w + 14)}", "                  y: 142",
                             f"                  width: {inner_w}", f"                  height: {L.STEPPER_H}",
                             f"                  widgets: [ {{ label: {{ align: CENTER,"
                             f" text: \"{sign} {abs(delta)}\", text_font: font_m }} }} ]",
                             "                  on_press:", "                    - script.execute: inactivity",
                             "                    - homeassistant.action:",
                             "                        action: climate.set_temperature",
                             "                        data:", f"                          entity_id: {e.entity}",
                             f"                          temperature: !lambda 'return id(p{pi}e{ei}_target).state"
                             f" {'+' if delta > 0 else '-'} {abs(delta)};'"]
                for role, attr in (("current", "current_temperature"), ("target", "temperature")):
                    lbl = "now" if role == "current" else "set"
                    self.sensors.append(
                        f"  - platform: homeassistant\n    id: p{pi}e{ei}_{role}\n"
                        f"    entity_id: {e.entity}\n    attribute: {attr}\n"
                        f"    on_value: {{ then: [ lvgl.widget.refresh: p{pi}e{ei}_{lbl} ] }}")
            out.append((title, page.icon, pid, body))
        return out

    # -- Readouts -----------------------------------------------------------
    def _page_readouts(self, pi, page):
        out = []
        for sp, placed in enumerate(L.paginate_readouts(page.entities, page.columns)):
            pid = f"page_p{pi}_{sp}"
            title = page.title if sp == 0 else f"{page.title} {sp + 1}"
            ids = [f"p{pi}e{page.entities.index(t.item)}_val" for t in placed]
            body = [f"    - id: {pid}", "      bg_color: ${paper}", "      bg_opa: COVER",
                    "      on_load:", "        - lambda: 'if (id(ui_ready)) id(last_page) = PAGEIDX;'",
                    f"        - lvgl.widget.refresh: [{', '.join(ids)}]",
                    "      widgets:",
                    f"        - label: {{ x: {L.MARGIN}, y: {L.HEADING_Y}, styles: heading,"
                    f" text: {_q(page.title)} }}"]
            for t in placed:
                e = t.item
                ei = page.entities.index(e)
                self.g.add("icon_m", e.icon)
                vfont = "font_l" if page.columns == 1 else "font_m"
                if page.columns == 1:
                    inner = [f"              - label: {{ align: LEFT_MID, text: {_lit(icons.escape(e.icon))},"
                             " text_font: icon_m }",
                             f"              - label: {{ align: LEFT_MID, x: 48, text: {_q(e.label)},"
                             " text_font: font_s }",
                             "              - label:", f"                  id: p{pi}e{ei}_val",
                             "                  align: RIGHT_MID", f"                  text_font: {vfont}"]
                else:
                    inner = [f"              - label: {{ x: 0, y: 0, text: {_lit(icons.escape(e.icon))},"
                             " text_font: icon_m }",
                             f"              - label: {{ x: 0, y: 40, text: {_q(e.label)}, text_font: font_s }}",
                             "              - label:", f"                  id: p{pi}e{ei}_val",
                             "                  align: TOP_RIGHT", f"                  text_font: {vfont}"]
                if len(e.entity) == 1:
                    inner.append(
                        f"                  text: !lambda 'const float v = id(p{pi}e{ei}_src0).state;"
                        f" return std::isnan(v) ? std::string(\"--\") : str_sprintf({_q(e.format[0])}, v);'")
                else:
                    inner += ["                  text: !lambda |-",
                              f"                    const float a = id(p{pi}e{ei}_src0).state,"
                              f" b = id(p{pi}e{ei}_src1).state;",
                              "                    if (std::isnan(a) && std::isnan(b)) return std::string(\"--\");",
                              "                    const float av = std::isnan(a) ? 0.0f : a,"
                              " bv = std::isnan(b) ? 0.0f : b;",
                              f"                    return bv > av ? str_sprintf({_q(e.format[1])}, bv)",
                              f"                                  : str_sprintf({_q(e.format[0])}, av);"]
                body += self.card(t.x, t.y, t.w, t.h, pad=12) + inner
                for k, ent in enumerate(e.entity):
                    attr = f"\n    attribute: {e.attribute[k]}" if e.attribute[k] else ""
                    self.sensors.append(
                        f"  - platform: homeassistant\n    id: p{pi}e{ei}_src{k}\n"
                        f"    entity_id: {ent}{attr}")
            self.intervals.append(
                f"  - interval: 60s\n    then:\n      - if:\n          condition:\n"
                f"            lambda: 'return lv_screen_active() == id({pid})->obj;'\n"
                f"          then: [ lvgl.widget.refresh: [{', '.join(ids)}] ]")
            out.append((title, page.icon, pid, body))
        return out

    # -- Media --------------------------------------------------------------
    def _page_media(self, pi, page):
        pid = f"page_p{pi}_0"
        self.g.add("icon_m", "television")
        self.g.add("icon_l", *icons.MEDIA_TRANSPORT)
        body = [f"    - id: {pid}", "      bg_color: ${paper}", "      bg_opa: COVER",
                "      on_load:", "        - lambda: 'if (id(ui_ready)) id(last_page) = PAGEIDX;'",
                f"        - lvgl.widget.refresh: [p{pi}_state, p{pi}_title]",
                "      widgets:",
                f"        - label: {{ x: {L.MARGIN}, y: {L.HEADING_Y}, styles: heading,"
                f" text: {_q(page.title)} }}"]
        body += self.card(L.MARGIN, L.CARD_TOP, L.CONTENT_W, L.MEDIA_CARD_H) + [
            f"              - label: {{ x: 0, y: 2, text: {_lit(icons.escape('television'))}, text_font: icon_m }}",
            f"              - label: {{ x: 48, y: 6, text: {_q(page.label)}, text_font: font_m }}",
            "              - label:", f"                  id: p{pi}_title", "                  x: 0",
            "                  y: 62", "                  width: 386", "                  long_mode: WRAP",
            "                  text_font: font_s",
            f"                  text: !lambda 'return id(p{pi}_title_src).state;'",
            "              - label:", f"                  id: p{pi}_state",
            "                  align: BOTTOM_LEFT", "                  text_font: font_s",
            f"                  text: !lambda 'return id(p{pi}_state_src).state;'"]
        actions = [("skip-previous", "media_previous_track"), ("play-pause", "media_play_pause"),
                   ("skip-next", "media_next_track"), ("volume-minus", "volume_down"),
                   ("volume-off", "volume_mute"), ("volume-plus", "volume_up")]
        for i, (icon, action) in enumerate(actions):
            x, y = L.MEDIA_BTN_X[i % 3], L.MEDIA_ROW_Y[i // 3]
            press = ["on_press:", "  - script.execute: inactivity"]
            if action == "volume_mute":
                # media_player.volume_mute REQUIRES is_volume_muted, and it sets an
                # absolute state rather than toggling - so send the inverse of what
                # the player currently reports.
                press += ["  - homeassistant.action:",
                          f"      action: media_player.{action}",
                          "      data_template:",
                          f"        entity_id: {page.entity}",
                          '        is_volume_muted: "{{ muted }}"',
                          "      variables:",
                          f"        muted: !lambda 'return id(p{pi}_muted).state"
                          ' ? std::string("false") : std::string("true");\'']
            else:
                press += [f"  - homeassistant.action: {{ action: media_player.{action},"
                          f" data: {{ entity_id: {page.entity} }} }}"]
            body += self.button(x, y, L.MEDIA_BTN_W, L.MEDIA_BTN_H, extra=[
                f"widgets: [ {{ label: {{ align: CENTER, text: {_lit(icons.escape(icon))},"
                " text_font: icon_l } } ]", *press])
        self.binary_sensors.append(
            f"  - platform: homeassistant\n    id: p{pi}_muted\n"
            f"    entity_id: {page.entity}\n    attribute: is_volume_muted")
        for role, attr in (("state", None), ("title", "media_title")):
            a = f"\n    attribute: {attr}" if attr else ""
            self.text_sensors.append(
                f"  - platform: homeassistant\n    id: p{pi}_{role}_src\n"
                f"    entity_id: {page.entity}{a}\n"
                f"    on_value: {{ then: [ lvgl.widget.refresh: p{pi}_{role} ] }}")
        return [(page.title, page.icon, pid, body)]

    # -- Settings (always present, not configurable) -------------------------
    def _page_settings(self, pi):
        self.g.add("icon_m", *icons.SETTINGS_ICONS)
        i = {n: icons.escape(n) for n in icons.SETTINGS_ICONS}
        pid = "page_settings"
        body = [f"    - id: {pid}", "      bg_color: ${paper}", "      bg_opa: COVER",
                "      on_load:", "        - lambda: 'if (id(ui_ready)) id(last_page) = PAGEIDX;'",
                "        - lvgl.widget.refresh: [timeout_lbl]",
                "        - lvgl.widget.update:", "            id: keep_awake_btn",
                "            state: { checked: !lambda 'return id(keep_awake).state;' }",
                "      widgets:",
                f"        - label: {{ x: {L.MARGIN}, y: {L.HEADING_Y}, styles: heading, text: \"Settings\" }}"]
        body += self.card(L.MARGIN, L.CARD_TOP, L.CONTENT_W, 230) + [
            f"              - label: {{ x: 0, y: 2, text: {_lit(i['brightness-6'])}, text_font: icon_m }}",
            "              - label: { x: 48, y: 6, text: \"Frontlight\", text_font: font_m }"]
        for sid, lbl, ly, sy, act in (
            ("fl_brightness", "Brightness", 52, 82, None),
            ("fl_warmth", "Warmth", 126, 156, "warmth")):
            body += [f"              - label: {{ x: 0, y: {ly}, text: {_q(lbl)}, text_font: font_s }}",
                     "              - slider:", f"                  id: {sid}",
                     "                  x: 0", f"                  y: {sy}",
                     "                  width: 386", "                  height: 32",
                     "                  radius: 4", "                  min_value: 0",
                     "                  max_value: 100",
                     *(["                  value: 50"] if act else []),
                     "                  bg_color: ${paper}", "                  border_color: ${ink}",
                     "                  border_width: 2",
                     "                  indicator: { bg_color: \"${ink}\", radius: 4 }",
                     # The knob is not drawn: it needs half its width of travel room at
                     # each end, which is exactly what stops the fill sitting flush left.
                     "                  knob: { bg_opa: TRANSP, border_width: 0, pad_all: 0 }",
                     "                  on_release:", "                    - script.execute: inactivity"]
            if act:
                body += ["                    - light.turn_on:", "                        id: frontlight",
                         "                        color_temperature: !lambda 'return 153 + x * (370 - 153) / 100.0;'"]
            else:
                body += ["                    - if:",
                         "                        condition: { lambda: 'return x < 1;' }",
                         "                        then: { light.turn_off: frontlight }", "                        else:",
                         "                          - light.turn_on:", "                              id: frontlight",
                         "                              brightness: !lambda 'return x / 100.0;'"]
        body += self.card(L.MARGIN, 340, L.CONTENT_W, 150) + [
            f"              - label: {{ x: 0, y: 2, text: {_lit(i['timer-outline'])}, text_font: icon_m }}",
            "              - label: { x: 48, y: 6, text: \"Sleep timeout\", text_font: font_m }",
            "              - label:", "                  id: timeout_lbl", "                  align: TOP_RIGHT",
            "                  text_font: font_l",
            "                  text: !lambda 'return str_sprintf(\"%.0f s\", id(sleep_timeout).state);'"]
        for k, (sign, op) in enumerate((("\\u2212", "decrement"), ("+", "increment"))):
            body += ["              - button:", "                  styles: navbtn",
                     "                  pressed: { styles: tile_on }",
                     f"                  x: {k * 200}", "                  y: 52",
                     "                  width: 186", "                  height: 64",
                     f"                  widgets: [ {{ label: {{ align: CENTER, text: \"{sign}\","
                     " text_font: font_step } } ]",
                     "                  on_press:", "                    - script.execute: inactivity",
                     f"                    - number.{op}: sleep_timeout",
                     "                    - lvgl.widget.refresh: timeout_lbl"]
        for x, style, gid, lbl, extra in (
            (30, "tile", i["eye"], "Keep awake",
             ["id: keep_awake_btn", "checked: { styles: tile_on }"]),
            (250, "navbtn", i["refresh"], "Full refresh", [])):
            press = (["on_press:", "  - switch.toggle: keep_awake",
                      "  - lvgl.widget.update:", "      id: keep_awake_btn", "      state:",
                      "        checked: !lambda 'return id(keep_awake).state;'",
                      "  - script.execute: inactivity"] if lbl == "Keep awake" else
                     ["on_press:", "  - script.execute: inactivity", "  - lambda: |-",
                      "      id(clean_mark) = id(epd).update_count + 1;",
                      "      id(epd).set_refresh_mode(0);", "      id(epd).update();"])
            body += self.button(x, 510, 200, 96, style, extra=[
                "pad_all: 6", *extra, "layout:", "  type: FLEX", "  flex_flow: COLUMN",
                "  flex_align_main: CENTER", "  flex_align_cross: CENTER",
                "  flex_align_track: CENTER", "  pad_row: 4", "widgets:",
                f"  - label: {{ text: {_lit(gid)}, text_font: icon_m }}",
                f"  - label: {{ text: {_q(lbl)}, text_font: font_s }}", *press])
        return [("Settings", "cog", pid, body)]

    def _sensor(self, entity, attribute=None):
        sid = "sum_" + entity.replace(".", "_") + (f"_{attribute}" if attribute else "")
        attr = f"\n    attribute: {attribute}" if attribute else ""
        line = f"  - platform: homeassistant\n    id: {sid}\n    entity_id: {entity}{attr}"
        if line not in self.sensors:
            self.sensors.append(line)
        return sid

    # --------------------------------------------------------------- assemble
    def _fonts(self):
        bat = [n for n, _ in icons.BATTERY] + [icons.BATTERY_EMPTY, icons.BATTERY_UNKNOWN]
        self.g.add("_battery18", *bat)
        f = ['font:',
             '  # Roboto for text, Material Design Icons for glyphs. MDI is fetched from the',
             '  # webfont at build time and cached. `extras` ADDS to ESPHome\'s default ASCII',
             '  # set; `glyphs` would replace it and silently break every heading.',
             '  - file: "gfonts://Roboto"', '    id: font_xs', '    size: 18', '    extras:',
             '      - file: &mdi "https://github.com/Templarian/MaterialDesign-Webfont/raw/master'
             '/fonts/materialdesignicons-webfont.ttf"',
             '        glyphs: [' + ', '.join(f'"\\U000{c}"' for _, c in self.g.items("_battery18")) + ']']
        for fid, size in (("font_s", 22), ("font_m", 28), ("font_l", 48)):
            f += [f'  - file: "gfonts://Roboto"', f'    id: {fid}', f'    size: {size}',
                  '    extras:', '      - file: "gfonts://Roboto"',
                  '        glyphs: ["\\u00B0", "\\u2212"]   # degree sign, minus sign']
        f += ['  - file: "gfonts://Roboto"', '    id: font_step', '    size: 34',
              '    glyphs: ["+", "\\u2212"]']
        for fid, size in (("icon_m", 36), ("icon_l", 48)):
            items = self.g.items(fid)
            if not items:
                items = [("cog", icons.codepoint("cog"))]
            # The comma must precede the comment: in a YAML flow sequence a '#'
            # comments out the rest of the line, separator included.
            rows = [f'"\\U000{c}",   # mdi-{n}' for n, c in items]
            rows[-1] = rows[-1].replace('",   #', '"]   #', 1)
            f += [f'  - file: *mdi', f'    id: {fid}', f'    size: {size}',
                  '    glyphs: [' + rows[0]]
            f += ['             ' + r for r in rows[1:]]
        return f

    def _assemble(self):
        w = self.w
        w(HEAD)
        w("substitutions:")
        w(f"  name: {self.p.name}")
        w(f"  friendly_name: {_q(self.p.friendly_name)}")
        w("")
        w("packages:")
        for k in ("hardware", "network", "power", "ui", "light_sleep"):
            w(f"  {k}: !include base/{k}.yaml")
        w("")
        w("esphome:")
        w("  name: ${name}")
        w("  friendly_name: ${friendly_name}")
        w("  on_boot:")
        w("    priority: -100")
        w("    then:")
        w("      - lambda: |-")
        w("          ui_detheme_all();")
        w("          int p = id(last_page);")
        w(f"          if (p > 0 && p < {len(self.pages)})")
        w("            id(lv)->show_page(p, LV_SCREEN_LOAD_ANIM_NONE, 0);")
        w("          id(ui_ready) = true;")
        w("")
        if self.globals:
            w("globals:")
            [w(g) for g in self.globals]
            w("")
        names = ", ".join(_q(t) for t, _, _, _ in self.pages)
        self.text_sensors.append(
            "  - platform: template\n    id: current_page\n    name: Current page\n"
            "    entity_category: diagnostic\n    update_interval: 5s\n    lambda: |-\n"
            f"      static const char *names[] = {{{names}}};\n"
            "      int i = id(last_page);\n"
            f"      return std::string((i >= 0 && i < {len(self.pages)}) ? names[i] : \"?\");")
        for name, items in (("sensor", self.sensors), ("binary_sensor", self.binary_sensors),
                            ("text_sensor", self.text_sensors),
                            ("script", self.scripts), ("interval", self.intervals)):
            if items:
                w(f"{name}:")
                [w(i) for i in items]
                w("")
        [w(l) for l in self._fonts()]
        w("")
        w("select:")
        w("  - platform: template")
        w("    id: page_select")
        w("    name: Page")
        w("    optimistic: true")
        w("    entity_category: config")
        w("    options: [" + ", ".join(_q(t) for t, _, _, _ in self.pages) + "]")
        w(f"    initial_option: {_q(self.pages[0][0])}")
        w("    set_action:")
        w("      - lambda: |-")
        w("          auto idx = id(page_select).index_of(x);")
        w("          if (idx.has_value()) {")
        w("            id(lv)->show_page(*idx, LV_SCREEN_LOAD_ANIM_NONE, 0);")
        w("            id(inactivity).execute();")
        w("          }")
        w("")
        w("lvgl:")
        w("  pages:")
        for idx, (_t, _i, _p, body) in enumerate(self.pages):
            for line in body:
                w(line.replace("PAGEIDX", str(idx)))
        return "\n".join(self.out) + "\n"


def generate(panel):
    return Emitter(panel).build()
